export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
  continent: string;
}

export const AIRPORTS: Airport[] = [
  // Africa
  { code: 'JNB', name: 'O. R. Tambo International Airport', city: 'Johannesburg', country: 'South Africa', continent: 'Africa' },
  { code: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', country: 'South Africa', continent: 'Africa' },
  { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo', country: 'Egypt', continent: 'Africa' },
  { code: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca', country: 'Morocco', continent: 'Africa' },
  { code: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos', country: 'Nigeria', continent: 'Africa' },
  { code: 'ACC', name: 'Kotoka International Airport', city: 'Accra', country: 'Ghana', continent: 'Africa' },
  { code: 'DSS', name: 'Blaise Diagne International Airport', city: 'Dakar', country: 'Senegal', continent: 'Africa' },
  { code: 'ADD', name: 'Addis Ababa Bole International Airport', city: 'Addis Ababa', country: 'Ethiopia', continent: 'Africa' },
  { code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', country: 'Kenya', continent: 'Africa' },
  { code: 'DAR', name: 'Julius Nyerere International Airport', city: 'Dar es Salaam', country: 'Tanzania', continent: 'Africa' },
  { code: 'EBB', name: 'Entebbe International Airport', city: 'Entebbe', country: 'Uganda', continent: 'Africa' },
  { code: 'TNR', name: 'Ivato International Airport', city: 'Antananarivo', country: 'Madagascar', continent: 'Africa' },
  { code: 'MRU', name: 'Sir Seewoosagur Ramgoolam Airport', city: 'Port Louis', country: 'Mauritius', continent: 'Africa' },
  { code: 'SEZ', name: 'Seychelles International Airport', city: 'Victoria', country: 'Seychelles', continent: 'Africa' },
  { code: 'ALG', name: 'Houari Boumediene Airport', city: 'Algiers', country: 'Algeria', continent: 'Africa' },
  { code: 'FIH', name: 'N\'Djili International Airport', city: 'Kinshasa', country: 'DR Congo', continent: 'Africa' },
  { code: 'KRT', name: 'Khartoum International Airport', city: 'Khartoum', country: 'Sudan', continent: 'Africa' },
  { code: 'LUN', name: 'Lusaka Kenneth Kaunda International Airport', city: 'Lusaka', country: 'Zambia', continent: 'Africa' },
  { code: 'HRE', name: 'Harare Robert Gabriel Mugabe Airport', city: 'Harare', country: 'Zimbabwe', continent: 'Africa' },
  { code: 'ROB', name: 'Roberts International Airport', city: 'Monrovia', country: 'Liberia', continent: 'Africa' },
  { code: 'LBV', name: 'Léon M\'ba International Airport', city: 'Libreville', country: 'Gabon', continent: 'Africa' },
  { code: 'DLA', name: 'Douala International Airport', city: 'Douala', country: 'Cameroon', continent: 'Africa' },
  { code: 'BZV', name: 'Maya-Maya Airport', city: 'Brazzaville', country: 'Republic of the Congo', continent: 'Africa' },
  { code: 'BGF', name: 'Bangui M\'Poko International Airport', city: 'Bangui', country: 'Central African Republic', continent: 'Africa' },
  { code: 'LAD', name: 'Quatro de Fevereiro Airport', city: 'Luanda', country: 'Angola', continent: 'Africa' },
  { code: 'SID', name: 'Sal International Airport', city: 'Sal', country: 'Cape Verde', continent: 'Africa' },
  { code: 'HAH', name: 'Moroni Prince Said Ibrahim Airport', city: 'Moroni', country: 'Comoros', continent: 'Africa' },
  { code: 'ABJ', name: 'Port Bouet Airport', city: 'Abidjan', country: 'Côte d\'Ivoire', continent: 'Africa' },
  { code: 'BKO', name: 'Modibo Keita International Airport', city: 'Bamako', country: 'Mali', continent: 'Africa' },
  { code: 'OUA', name: 'Ouagadougou Airport', city: 'Ouagadougou', country: 'Burkina Faso', continent: 'Africa' },
  { code: 'NIM', name: 'Niamey Diori Hamani International Airport', city: 'Niamey', country: 'Niger', continent: 'Africa' },
  { code: 'BJL', name: 'Banjul International Airport', city: 'Banjul', country: 'Gambia', continent: 'Africa' },
  { code: 'CKY', name: 'Conakry International Airport', city: 'Conakry', country: 'Guinea', continent: 'Africa' },
  { code: 'FNA', name: 'Lungi International Airport', city: 'Freetown', country: 'Sierra Leone', continent: 'Africa' },
  { code: 'TMS', name: 'São Tomé International Airport', city: 'São Tomé', country: 'São Tomé and Príncipe', continent: 'Africa' },
  { code: 'LFW', name: 'Lomé–Tokoin International Airport', city: 'Lomé', country: 'Togo', continent: 'Africa' },
  { code: 'NDJ', name: 'N\'Djamena International Airport', city: 'N\'Djamena', country: 'Chad', continent: 'Africa' },
  { code: 'TUN', name: 'Tunis–Carthage International Airport', city: 'Tunis', country: 'Tunisia', continent: 'Africa' },
  { code: 'JIB', name: 'Djibouti–Ambouli International Airport', city: 'Djibouti', country: 'Djibouti', continent: 'Africa' },
  { code: 'KGL', name: 'Kigali International Airport', city: 'Kigali', country: 'Rwanda', continent: 'Africa' },
  { code: 'BJM', name: 'Bujumbura International Airport', city: 'Bujumbura', country: 'Burundi', continent: 'Africa' },
  { code: 'ASM', name: 'Asmara International Airport', city: 'Asmara', country: 'Eritrea', continent: 'Africa' },

  // Asia
  { code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', continent: 'Asia' },
  { code: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China', continent: 'Asia' },
  { code: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', country: 'China', continent: 'Asia' },
  { code: 'SZX', name: 'Shenzhen Bao\'an International Airport', city: 'Shenzhen', country: 'China', continent: 'Asia' },
  { code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'Hong Kong', continent: 'Asia' },
  { code: 'HND', name: 'Tokyo Haneda Airport', city: 'Tokyo', country: 'Japan', continent: 'Asia' },
  { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan', continent: 'Asia' },
  { code: 'KIX', name: 'Kansai International Airport', city: 'Osaka', country: 'Japan', continent: 'Asia' },
  { code: 'ICN', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea', continent: 'Asia' },
  { code: 'GMP', name: 'Gimpo International Airport', city: 'Seoul', country: 'South Korea', continent: 'Asia' },
  { code: 'TPE', name: 'Taoyuan International Airport', city: 'Taipei', country: 'Taiwan', continent: 'Asia' },
  { code: 'KHH', name: 'Kaohsiung International Airport', city: 'Kaohsiung', country: 'Taiwan', continent: 'Asia' },
  { code: 'MNL', name: 'Manila Ninoy Aquino International Airport', city: 'Manila', country: 'Philippines', continent: 'Asia' },
  { code: 'CEB', name: 'Mactan–Cebu International Airport', city: 'Cebu', country: 'Philippines', continent: 'Asia' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', continent: 'Asia' },
  { code: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', country: 'Thailand', continent: 'Asia' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia', continent: 'Asia' },
  { code: 'PEN', name: 'Penang International Airport', city: 'Penang', country: 'Malaysia', continent: 'Asia' },
  { code: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', country: 'Singapore', continent: 'Asia' },
  { code: 'CGK', name: 'Soekarno–Hatta International Airport', city: 'Jakarta', country: 'Indonesia', continent: 'Asia' },
  { code: 'DPS', name: 'Ngurah Rai (Bali) International Airport', city: 'Denpasar', country: 'Indonesia', continent: 'Asia' },
  { code: 'HAN', name: 'Hanoi Noi Bai International Airport', city: 'Hanoi', country: 'Vietnam', continent: 'Asia' },
  { code: 'SGN', name: 'Ho Chi Minh Tan Son Nhat Airport', city: 'Ho Chi Minh City', country: 'Vietnam', continent: 'Asia' },
  { code: 'PNH', name: 'Phnom Penh International Airport', city: 'Phnom Penh', country: 'Cambodia', continent: 'Asia' },
  { code: 'RGN', name: 'Yangon International Airport', city: 'Yangon', country: 'Myanmar', continent: 'Asia' },
  { code: 'PBH', name: 'Paro International Airport', city: 'Paro', country: 'Bhutan', continent: 'Asia' },
  { code: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', country: 'Nepal', continent: 'Asia' },
  { code: 'DAC', name: 'Dhaka Shahjalal International Airport', city: 'Dhaka', country: 'Bangladesh', continent: 'Asia' },
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'New Delhi', country: 'India', continent: 'Asia' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India', continent: 'Asia' },
  { code: 'BLR', name: 'Kempegowda International Airport', city: 'Bangalore', country: 'India', continent: 'Asia' },
  { code: 'MAA', name: 'Chennai International Airport', city: 'Chennai', country: 'India', continent: 'Asia' },
  { code: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', country: 'India', continent: 'Asia' },
  { code: 'GOI', name: 'Goa Dabolim Airport', city: 'Goa', country: 'India', continent: 'Asia' },
  { code: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad', country: 'Pakistan', continent: 'Asia' },
  { code: 'KHI', name: 'Jinnah International Airport', city: 'Karachi', country: 'Pakistan', continent: 'Asia' },
  { code: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore', country: 'Pakistan', continent: 'Asia' },
  { code: 'KBL', name: 'Kabul Hamid Karzai International Airport', city: 'Kabul', country: 'Afghanistan', continent: 'Asia' },
  { code: 'IKA', name: 'Tehran Imam Khomeini International Airport', city: 'Tehran', country: 'Iran', continent: 'Asia' },
  { code: 'MHD', name: 'Mashhad International Airport', city: 'Mashhad', country: 'Iran', continent: 'Asia' },
  { code: 'GYD', name: 'Baku Heydar Aliyev International Airport', city: 'Baku', country: 'Azerbaijan', continent: 'Asia' },
  { code: 'TBS', name: 'Tbilisi International Airport', city: 'Tbilisi', country: 'Georgia', continent: 'Asia' },
  { code: 'EVN', name: 'Yerevan Zvartnots International Airport', city: 'Yerevan', country: 'Armenia', continent: 'Asia' },
  { code: 'ASB', name: 'Ashgabat International Airport', city: 'Ashgabat', country: 'Turkmenistan', continent: 'Asia' },
  { code: 'ALA', name: 'Almaty International Airport', city: 'Almaty', country: 'Kazakhstan', continent: 'Asia' },
  { code: 'NQZ', name: 'Astana Nursultan Nazarbayev International Airport', city: 'Nur-Sultan', country: 'Kazakhstan', continent: 'Asia' },
  { code: 'TAS', name: 'Tashkent Islam Karimov International Airport', city: 'Tashkent', country: 'Uzbekistan', continent: 'Asia' },
  { code: 'FRU', name: 'Bishkek Manas International Airport', city: 'Bishkek', country: 'Kyrgyzstan', continent: 'Asia' },
  { code: 'UBN', name: 'Ulaanbaatar Chinggis Khaan International Airport', city: 'Ulaanbaatar', country: 'Mongolia', continent: 'Asia' },

  // Middle East
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE', continent: 'Middle East' },
  { code: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', country: 'UAE', continent: 'Middle East' },
  { code: 'SHJ', name: 'Sharjah International Airport', city: 'Sharjah', country: 'UAE', continent: 'Middle East' },
  { code: 'DOH', name: 'Doha Hamad International Airport', city: 'Doha', country: 'Qatar', continent: 'Middle East' },
  { code: 'MCT', name: 'Muscat International Airport', city: 'Muscat', country: 'Oman', continent: 'Middle East' },
  { code: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', country: 'Saudi Arabia', continent: 'Middle East' },
  { code: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'Saudi Arabia', continent: 'Middle East' },
  { code: 'BAH', name: 'Bahrain International Airport', city: 'Manama', country: 'Bahrain', continent: 'Middle East' },
  { code: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', country: 'Kuwait', continent: 'Middle East' },
  { code: 'TLV', name: 'Ben Gurion International Airport', city: 'Tel Aviv', country: 'Israel', continent: 'Middle East' },
  { code: 'BEY', name: 'Beirut Rafic Hariri International Airport', city: 'Beirut', country: 'Lebanon', continent: 'Middle East' },
  { code: 'DAM', name: 'Damascus International Airport', city: 'Damascus', country: 'Syria', continent: 'Middle East' },
  { code: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', country: 'Jordan', continent: 'Middle East' },
  { code: 'BGW', name: 'Baghdad International Airport', city: 'Baghdad', country: 'Iraq', continent: 'Middle East' },
  { code: 'EBL', name: 'Erbil International Airport', city: 'Erbil', country: 'Iraq', continent: 'Middle East' },
  { code: 'NJF', name: 'Najaf Al Najaf International Airport', city: 'Najaf', country: 'Iraq', continent: 'Middle East' },
  { code: 'SAH', name: 'Sana\'a International Airport', city: 'Sana\'a', country: 'Yemen', continent: 'Middle East' },
  { code: 'ADE', name: 'Aden International Airport', city: 'Aden', country: 'Yemen', continent: 'Middle East' },
  { code: 'SLL', name: 'Salalah International Airport', city: 'Salalah', country: 'Oman', continent: 'Middle East' },

  // Europe
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey', continent: 'Europe' },
  { code: 'SAW', name: 'Sabiha Gökçen International Airport', city: 'Istanbul', country: 'Turkey', continent: 'Europe' },
  { code: 'AYT', name: 'Antalya Airport', city: 'Antalya', country: 'Turkey', continent: 'Europe' },
  { code: 'ATH', name: 'Athens Eleftherios Venizelos International Airport', city: 'Athens', country: 'Greece', continent: 'Europe' },
  { code: 'SKG', name: 'Thessaloniki Makedonia Airport', city: 'Thessaloniki', country: 'Greece', continent: 'Europe' },
  { code: 'LCA', name: 'Larnaca International Airport', city: 'Larnaca', country: 'Cyprus', continent: 'Europe' },
  { code: 'PFO', name: 'Paphos International Airport', city: 'Paphos', country: 'Cyprus', continent: 'Europe' },
  { code: 'LHR', name: 'London Heathrow Airport', city: 'London', country: 'United Kingdom', continent: 'Europe' },
  { code: 'LGW', name: 'London Gatwick Airport', city: 'London', country: 'United Kingdom', continent: 'Europe' },
  { code: 'MAN', name: 'Manchester Airport', city: 'Manchester', country: 'United Kingdom', continent: 'Europe' },
  { code: 'BHX', name: 'Birmingham Airport', city: 'Birmingham', country: 'United Kingdom', continent: 'Europe' },
  { code: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'United Kingdom', continent: 'Europe' },
  { code: 'GLA', name: 'Glasgow International Airport', city: 'Glasgow', country: 'United Kingdom', continent: 'Europe' },
  { code: 'BRS', name: 'Bristol Airport', city: 'Bristol', country: 'United Kingdom', continent: 'Europe' },
  { code: 'CDG', name: 'Paris Charles de Gaulle Airport', city: 'Paris', country: 'France', continent: 'Europe' },
  { code: 'ORY', name: 'Paris Orly Airport', city: 'Paris', country: 'France', continent: 'Europe' },
  { code: 'NCE', name: 'Nice Côte d\'Azur Airport', city: 'Nice', country: 'France', continent: 'Europe' },
  { code: 'LYS', name: 'Lyon–Saint-Exupéry Airport', city: 'Lyon', country: 'France', continent: 'Europe' },
  { code: 'MRS', name: 'Marseille Provence Airport', city: 'Marseille', country: 'France', continent: 'Europe' },
  { code: 'FRA', name: 'Frankfurt am Main Airport', city: 'Frankfurt', country: 'Germany', continent: 'Europe' },
  { code: 'MUC', name: 'Munich Airport', city: 'Munich', country: 'Germany', continent: 'Europe' },
  { code: 'DUS', name: 'Düsseldorf Airport', city: 'Düsseldorf', country: 'Germany', continent: 'Europe' },
  { code: 'BER', name: 'Berlin Brandenburg Airport', city: 'Berlin', country: 'Germany', continent: 'Europe' },
  { code: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', country: 'Germany', continent: 'Europe' },
  { code: 'CGN', name: 'Cologne Bonn Airport', city: 'Cologne', country: 'Germany', continent: 'Europe' },
  { code: 'AMS', name: 'Amsterdam Schiphol Airport', city: 'Amsterdam', country: 'Netherlands', continent: 'Europe' },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium', continent: 'Europe' },
  { code: 'ZUR', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland', continent: 'Europe' },
  { code: 'GVA', name: 'Geneva Airport', city: 'Geneva', country: 'Switzerland', continent: 'Europe' },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria', continent: 'Europe' },
  { code: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'Poland', continent: 'Europe' },
  { code: 'KRK', name: 'Kraków John Paul II International Airport', city: 'Kraków', country: 'Poland', continent: 'Europe' },
  { code: 'GDN', name: 'Gdańsk Lech Wałęsa Airport', city: 'Gdańsk', country: 'Poland', continent: 'Europe' },
  { code: 'PRG', name: 'Prague Václav Havel Airport', city: 'Prague', country: 'Czech Republic', continent: 'Europe' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary', continent: 'Europe' },
  { code: 'OTP', name: 'Bucharest Henri Coandă International Airport', city: 'Bucharest', country: 'Romania', continent: 'Europe' },
  { code: 'SOF', name: 'Sofia Airport', city: 'Sofia', country: 'Bulgaria', continent: 'Europe' },
  { code: 'BEG', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade', country: 'Serbia', continent: 'Europe' },
  { code: 'SKP', name: 'Skopje International Airport', city: 'Skopje', country: 'North Macedonia', continent: 'Europe' },
  { code: 'TIA', name: 'Tirana International Airport', city: 'Tirana', country: 'Albania', continent: 'Europe' },
  { code: 'SJJ', name: 'Sarajevo International Airport', city: 'Sarajevo', country: 'Bosnia and Herzegovina', continent: 'Europe' },
  { code: 'TGD', name: 'Podgorica Airport', city: 'Podgorica', country: 'Montenegro', continent: 'Europe' },
  { code: 'LJU', name: 'Ljubljana Jože Pučnik Airport', city: 'Ljubljana', country: 'Slovenia', continent: 'Europe' },
  { code: 'ZAG', name: 'Zagreb Franjo Tuđman Airport', city: 'Zagreb', country: 'Croatia', continent: 'Europe' },
  { code: 'RIX', name: 'Riga International Airport', city: 'Riga', country: 'Latvia', continent: 'Europe' },
  { code: 'VNO', name: 'Vilnius International Airport', city: 'Vilnius', country: 'Lithuania', continent: 'Europe' },
  { code: 'TLL', name: 'Tallinn Airport', city: 'Tallinn', country: 'Estonia', continent: 'Europe' },
  { code: 'HEL', name: 'Helsinki-Vantaa Airport', city: 'Helsinki', country: 'Finland', continent: 'Europe' },
  { code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', country: 'Sweden', continent: 'Europe' },
  { code: 'GOT', name: 'Gothenburg Landvetter Airport', city: 'Gothenburg', country: 'Sweden', continent: 'Europe' },
  { code: 'OSL', name: 'Oslo Gardermoen Airport', city: 'Oslo', country: 'Norway', continent: 'Europe' },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark', continent: 'Europe' },
  { code: 'KEF', name: 'Reykjavik Keflavik International Airport', city: 'Reykjavik', country: 'Iceland', continent: 'Europe' },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland', continent: 'Europe' },
  { code: 'SNN', name: 'Shannon Airport', city: 'Shannon', country: 'Ireland', continent: 'Europe' },
  { code: 'LIS', name: 'Lisbon Humberto Delgado Airport', city: 'Lisbon', country: 'Portugal', continent: 'Europe' },
  { code: 'FNC', name: 'Madeira Cristiano Ronaldo Airport', city: 'Funchal', country: 'Portugal', continent: 'Europe' },
  { code: 'OPO', name: 'Porto Francisco Sá Carneiro Airport', city: 'Porto', country: 'Portugal', continent: 'Europe' },
  { code: 'MAD', name: 'Madrid Barajas Airport', city: 'Madrid', country: 'Spain', continent: 'Europe' },
  { code: 'BCN', name: 'Barcelona El Prat Airport', city: 'Barcelona', country: 'Spain', continent: 'Europe' },
  { code: 'VLC', name: 'Valencia Airport', city: 'Valencia', country: 'Spain', continent: 'Europe' },
  { code: 'SVQ', name: 'Seville San Pablo Airport', city: 'Seville', country: 'Spain', continent: 'Europe' },
  { code: 'BIO', name: 'Bilbao Airport', city: 'Bilbao', country: 'Spain', continent: 'Europe' },
  { code: 'LPA', name: 'Gran Canaria Airport', city: 'Las Palmas', country: 'Spain', continent: 'Europe' },
  { code: 'TFS', name: 'Tenerife South Airport', city: 'Tenerife', country: 'Spain', continent: 'Europe' },
  { code: 'FCO', name: 'Rome Fiumicino Leonardo da Vinci Airport', city: 'Rome', country: 'Italy', continent: 'Europe' },
  { code: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', country: 'Italy', continent: 'Europe' },
  { code: 'VCE', name: 'Venice Marco Polo Airport', city: 'Venice', country: 'Italy', continent: 'Europe' },
  { code: 'NAP', name: 'Naples International Airport', city: 'Naples', country: 'Italy', continent: 'Europe' },
  { code: 'BLQ', name: 'Bologna Guglielmo Marconi Airport', city: 'Bologna', country: 'Italy', continent: 'Europe' },
  { code: 'PMO', name: 'Palermo Falcone–Borsellino Airport', city: 'Palermo', country: 'Italy', continent: 'Europe' },
  { code: 'MLA', name: 'Malta International Airport', city: 'Valletta', country: 'Malta', continent: 'Europe' },

  // North America
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', continent: 'North America' },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', continent: 'North America' },
  { code: 'YUL', name: 'Montréal–Trudeau International Airport', city: 'Montreal', country: 'Canada', continent: 'North America' },
  { code: 'YYC', name: 'Calgary International Airport', city: 'Calgary', country: 'Canada', continent: 'North America' },
  { code: 'YOW', name: 'Ottawa Macdonald–Cartier International Airport', city: 'Ottawa', country: 'Canada', continent: 'North America' },
  { code: 'YEG', name: 'Edmonton International Airport', city: 'Edmonton', country: 'Canada', continent: 'North America' },
  { code: 'YQB', name: 'Quebec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', continent: 'North America' },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', continent: 'North America' },
  { code: 'YWG', name: 'Winnipeg James Armstrong Richardson Airport', city: 'Winnipeg', country: 'Canada', continent: 'North America' },
  { code: 'YYT', name: 'St. John\'s International Airport', city: 'St. John\'s', country: 'Canada', continent: 'North America' },
  { code: 'ATL', name: 'Hartsfield–Jackson Atlanta International Airport', city: 'Atlanta', country: 'United States', continent: 'North America' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'United States', continent: 'North America' },
  { code: 'ORD', name: 'Chicago O\'Hare International Airport', city: 'Chicago', country: 'United States', continent: 'North America' },
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'United States', continent: 'North America' },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'United States', continent: 'North America' },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', country: 'United States', continent: 'North America' },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'United States', continent: 'North America' },
  { code: 'SEA', name: 'Seattle–Tacoma International Airport', city: 'Seattle', country: 'United States', continent: 'North America' },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', country: 'United States', continent: 'North America' },
  { code: 'MCO', name: 'Orlando International Airport', city: 'Orlando', country: 'United States', continent: 'North America' },
  { code: 'BOS', name: 'Boston Logan International Airport', city: 'Boston', country: 'United States', continent: 'North America' },
  { code: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'United States', continent: 'North America' },
  { code: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', country: 'United States', continent: 'North America' },
  { code: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', country: 'United States', continent: 'North America' },
  { code: 'MSP', name: 'Minneapolis–Saint Paul International Airport', city: 'Minneapolis', country: 'United States', continent: 'North America' },
  { code: 'DTW', name: 'Detroit Metropolitan Airport', city: 'Detroit', country: 'United States', continent: 'North America' },
  { code: 'BWI', name: 'Baltimore/Washington International Airport', city: 'Baltimore', country: 'United States', continent: 'North America' },
  { code: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington DC', country: 'United States', continent: 'North America' },
  { code: 'LGA', name: 'LaGuardia Airport', city: 'New York', country: 'United States', continent: 'North America' },
  { code: 'IAH', name: 'Houston George Bush Intercontinental Airport', city: 'Houston', country: 'United States', continent: 'North America' },
  { code: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', country: 'United States', continent: 'North America' },
  { code: 'TPA', name: 'Tampa International Airport', city: 'Tampa', country: 'United States', continent: 'North America' },
  { code: 'PDX', name: 'Portland International Airport', city: 'Portland', country: 'United States', continent: 'North America' },
  { code: 'SAN', name: 'San Diego International Airport', city: 'San Diego', country: 'United States', continent: 'North America' },
  { code: 'RDU', name: 'Raleigh–Durham International Airport', city: 'Raleigh', country: 'United States', continent: 'North America' },
  { code: 'AUS', name: 'Austin–Bergstrom International Airport', city: 'Austin', country: 'United States', continent: 'North America' },
  { code: 'BNA', name: 'Nashville International Airport', city: 'Nashville', country: 'United States', continent: 'North America' },
  { code: 'HNL', name: 'Honolulu Daniel K. Inouye International Airport', city: 'Honolulu', country: 'United States', continent: 'North America' },
  { code: 'ANC', name: 'Anchorage Ted Stevens International Airport', city: 'Anchorage', country: 'United States', continent: 'North America' },
  { code: 'SJC', name: 'San Jose Mineta International Airport', city: 'San Jose', country: 'United States', continent: 'North America' },
  { code: 'STL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', country: 'United States', continent: 'North America' },
  { code: 'MCI', name: 'Kansas City International Airport', city: 'Kansas City', country: 'United States', continent: 'North America' },
  { code: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', country: 'United States', continent: 'North America' },
  { code: 'PIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', country: 'United States', continent: 'North America' },
  { code: 'MSY', name: 'New Orleans Louis Armstrong Airport', city: 'New Orleans', country: 'United States', continent: 'North America' },
  { code: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', country: 'United States', continent: 'North America' },
  { code: 'MEX', name: 'Mexico City Benito Juárez International Airport', city: 'Mexico City', country: 'Mexico', continent: 'North America' },
  { code: 'CUN', name: 'Cancún International Airport', city: 'Cancún', country: 'Mexico', continent: 'North America' },
  { code: 'GDL', name: 'Guadalajara Miguel Hidalgo y Costilla Airport', city: 'Guadalajara', country: 'Mexico', continent: 'North America' },
  { code: 'MTY', name: 'Monterrey General Mariano Escobedo Airport', city: 'Monterrey', country: 'Mexico', continent: 'North America' },
  { code: 'TIJ', name: 'Tijuana International Airport', city: 'Tijuana', country: 'Mexico', continent: 'North America' },
  { code: 'HMO', name: 'Hermosillo International Airport', city: 'Hermosillo', country: 'Mexico', continent: 'North America' },
  { code: 'PVR', name: 'Puerto Vallarta International Airport', city: 'Puerto Vallarta', country: 'Mexico', continent: 'North America' },
  { code: 'SJD', name: 'Los Cabos International Airport', city: 'Los Cabos', country: 'Mexico', continent: 'North America' },

  // Central America & Caribbean
  { code: 'SJO', name: 'San José Juan Santamaría International Airport', city: 'San José', country: 'Costa Rica', continent: 'North America' },
  { code: 'PTY', name: 'Panama City Tocumen International Airport', city: 'Panama City', country: 'Panama', continent: 'North America' },
  { code: 'SAL', name: 'San Salvador El Salvador International Airport', city: 'San Salvador', country: 'El Salvador', continent: 'North America' },
  { code: 'GUA', name: 'Guatemala City La Aurora International Airport', city: 'Guatemala City', country: 'Guatemala', continent: 'North America' },
  { code: 'TGU', name: 'Tegucigalpa Toncontín International Airport', city: 'Tegucigalpa', country: 'Honduras', continent: 'North America' },
  { code: 'MGA', name: 'Managua Augusto C. Sandino International Airport', city: 'Managua', country: 'Nicaragua', continent: 'North America' },
  { code: 'HAV', name: 'Havana José Martí International Airport', city: 'Havana', country: 'Cuba', continent: 'North America' },
  { code: 'VRA', name: 'Varadero Juan Gualberto Gómez Airport', city: 'Varadero', country: 'Cuba', continent: 'North America' },
  { code: 'SDQ', name: 'Santo Domingo Las Américas International Airport', city: 'Santo Domingo', country: 'Dominican Republic', continent: 'North America' },
  { code: 'PUJ', name: 'Punta Cana International Airport', city: 'Punta Cana', country: 'Dominican Republic', continent: 'North America' },
  { code: 'PAP', name: 'Port-au-Prince Toussaint Louverture International Airport', city: 'Port-au-Prince', country: 'Haiti', continent: 'North America' },
  { code: 'SJU', name: 'San Juan Luis Muñoz Marín International Airport', city: 'San Juan', country: 'Puerto Rico', continent: 'North America' },
  { code: 'KIN', name: 'Kingston Norman Manley International Airport', city: 'Kingston', country: 'Jamaica', continent: 'North America' },
  { code: 'MBJ', name: 'Montego Bay Sangster International Airport', city: 'Montego Bay', country: 'Jamaica', continent: 'North America' },
  { code: 'NAS', name: 'Nassau Lynden Pindling International Airport', city: 'Nassau', country: 'Bahamas', continent: 'North America' },
  { code: 'PLS', name: 'Providenciales International Airport', city: 'Providenciales', country: 'Turks and Caicos', continent: 'North America' },
  { code: 'POS', name: 'Port of Spain Piarco International Airport', city: 'Port of Spain', country: 'Trinidad and Tobago', continent: 'North America' },
  { code: 'BGI', name: 'Bridgetown Grantley Adams International Airport', city: 'Bridgetown', country: 'Barbados', continent: 'North America' },
  { code: 'SLU', name: 'Castries George F. L. Charles Airport', city: 'Castries', country: 'Saint Lucia', continent: 'North America' },
  { code: 'ANU', name: 'St. John\'s V. C. Bird International Airport', city: 'St. John\'s', country: 'Antigua and Barbuda', continent: 'North America' },
  { code: 'SVD', name: 'Kingstown Argyle International Airport', city: 'Kingstown', country: 'Saint Vincent and the Grenadines', continent: 'North America' },

  // South America
  { code: 'GEO', name: 'Georgetown Cheddi Jagan International Airport', city: 'Georgetown', country: 'Guyana', continent: 'South America' },
  { code: 'PBM', name: 'Paramaribo Johan Adolf Pengel Airport', city: 'Paramaribo', country: 'Suriname', continent: 'South America' },
  { code: 'CCS', name: 'Caracas Simón Bolívar International Airport', city: 'Caracas', country: 'Venezuela', continent: 'South America' },
  { code: 'BOG', name: 'Bogotá El Dorado International Airport', city: 'Bogotá', country: 'Colombia', continent: 'South America' },
  { code: 'MDE', name: 'Medellín José María Córdova International Airport', city: 'Medellín', country: 'Colombia', continent: 'South America' },
  { code: 'CLO', name: 'Cali Alfonso Bonilla Aragón International Airport', city: 'Cali', country: 'Colombia', continent: 'South America' },
  { code: 'UIO', name: 'Quito Mariscal Sucre International Airport', city: 'Quito', country: 'Ecuador', continent: 'South America' },
  { code: 'GYE', name: 'Guayaquil José Joaquín de Olmedo Airport', city: 'Guayaquil', country: 'Ecuador', continent: 'South America' },
  { code: 'LIM', name: 'Lima Jorge Chávez International Airport', city: 'Lima', country: 'Peru', continent: 'South America' },
  { code: 'AQP', name: 'Arequipa Rodríguez Ballón International Airport', city: 'Arequipa', country: 'Peru', continent: 'South America' },
  { code: 'CUZ', name: 'Cusco Alejandro Velasco Astete International Airport', city: 'Cusco', country: 'Peru', continent: 'South America' },
  { code: 'SCL', name: 'Santiago Arturo Merino Benítez International Airport', city: 'Santiago', country: 'Chile', continent: 'South America' },
  { code: 'IQQ', name: 'Iquique Diego Aracena International Airport', city: 'Iquique', country: 'Chile', continent: 'South America' },
  { code: 'EZE', name: 'Buenos Aires Ministro Pistarini Ezeiza Airport', city: 'Buenos Aires', country: 'Argentina', continent: 'South America' },
  { code: 'AEP', name: 'Buenos Aires Aeroparque Jorge Newbery', city: 'Buenos Aires', country: 'Argentina', continent: 'South America' },
  { code: 'COR', name: 'Córdoba Ingeniero Aeronáutico Ambrosio L.V. Taravella Airport', city: 'Córdoba', country: 'Argentina', continent: 'South America' },
  { code: 'ROS', name: 'Rosario Islas Malvinas International Airport', city: 'Rosario', country: 'Argentina', continent: 'South America' },
  { code: 'MVD', name: 'Montevideo Carrasco International Airport', city: 'Montevideo', country: 'Uruguay', continent: 'South America' },
  { code: 'ASU', name: 'Asunción Silvio Pettirossi International Airport', city: 'Asunción', country: 'Paraguay', continent: 'South America' },
  { code: 'GRU', name: 'São Paulo Guarulhos International Airport', city: 'São Paulo', country: 'Brazil', continent: 'South America' },
  { code: 'GIG', name: 'Rio de Janeiro Galeão International Airport', city: 'Rio de Janeiro', country: 'Brazil', continent: 'South America' },
  { code: 'BSB', name: 'Brasília International Airport', city: 'Brasília', country: 'Brazil', continent: 'South America' },
  { code: 'CNF', name: 'Belo Horizonte Tancredo Neves Airport', city: 'Belo Horizonte', country: 'Brazil', continent: 'South America' },
  { code: 'SSA', name: 'Salvador Deputado Luís Eduardo Magalhães Airport', city: 'Salvador', country: 'Brazil', continent: 'South America' },
  { code: 'POA', name: 'Porto Alegre Salgado Filho International Airport', city: 'Porto Alegre', country: 'Brazil', continent: 'South America' },
  { code: 'REC', name: 'Recife Guararapes–Gilberto Freyre International Airport', city: 'Recife', country: 'Brazil', continent: 'South America' },
  { code: 'FOR', name: 'Fortaleza Pinto Martins International Airport', city: 'Fortaleza', country: 'Brazil', continent: 'South America' },
  { code: 'MAO', name: 'Manaus Eduardo Gomes International Airport', city: 'Manaus', country: 'Brazil', continent: 'South America' },
  { code: 'BEL', name: 'Belém Val de Cans International Airport', city: 'Belém', country: 'Brazil', continent: 'South America' },
  { code: 'CGB', name: 'Cuiabá Marechal Rondon International Airport', city: 'Cuiabá', country: 'Brazil', continent: 'South America' },
  { code: 'CGR', name: 'Campo Grande International Airport', city: 'Campo Grande', country: 'Brazil', continent: 'South America' },
  { code: 'GYN', name: 'Goiânia Santa Genoveva Airport', city: 'Goiânia', country: 'Brazil', continent: 'South America' },
  { code: 'PMW', name: 'Palmas Airport', city: 'Palmas', country: 'Brazil', continent: 'South America' },
  { code: 'MCP', name: 'Macapá International Airport', city: 'Macapá', country: 'Brazil', continent: 'South America' },
  { code: 'THE', name: 'Teresina Airport', city: 'Teresina', country: 'Brazil', continent: 'South America' },
  { code: 'AJU', name: 'Aracaju Santa Maria Airport', city: 'Aracaju', country: 'Brazil', continent: 'South America' },
  { code: 'BVB', name: 'Boa Vista Atlas Brasil Cantanhede Airport', city: 'Boa Vista', country: 'Brazil', continent: 'South America' },
  { code: 'PVH', name: 'Porto Velho International Airport', city: 'Porto Velho', country: 'Brazil', continent: 'South America' },
  { code: 'RBR', name: 'Rio Branco International Airport', city: 'Rio Branco', country: 'Brazil', continent: 'South America' },
  { code: 'LPB', name: 'La Paz El Alto International Airport', city: 'La Paz', country: 'Bolivia', continent: 'South America' },
  { code: 'VVI', name: 'Santa Cruz Viru Viru International Airport', city: 'Santa Cruz', country: 'Bolivia', continent: 'South America' },
  { code: 'SRE', name: 'Sucre Alcantarí International Airport', city: 'Sucre', country: 'Bolivia', continent: 'South America' },

  // Oceania
  { code: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', country: 'Australia', continent: 'Oceania' },
  { code: 'MEL', name: 'Melbourne Tullamarine Airport', city: 'Melbourne', country: 'Australia', continent: 'Oceania' },
  { code: 'BNE', name: 'Brisbane Airport', city: 'Brisbane', country: 'Australia', continent: 'Oceania' },
  { code: 'PER', name: 'Perth Airport', city: 'Perth', country: 'Australia', continent: 'Oceania' },
  { code: 'ADL', name: 'Adelaide Airport', city: 'Adelaide', country: 'Australia', continent: 'Oceania' },
  { code: 'OOL', name: 'Gold Coast Airport', city: 'Gold Coast', country: 'Australia', continent: 'Oceania' },
  { code: 'CBR', name: 'Canberra Airport', city: 'Canberra', country: 'Australia', continent: 'Oceania' },
  { code: 'HBA', name: 'Hobart Airport', city: 'Hobart', country: 'Australia', continent: 'Oceania' },
  { code: 'DRW', name: 'Darwin International Airport', city: 'Darwin', country: 'Australia', continent: 'Oceania' },
  { code: 'AKL', name: 'Auckland Airport', city: 'Auckland', country: 'New Zealand', continent: 'Oceania' },
  { code: 'WLG', name: 'Wellington International Airport', city: 'Wellington', country: 'New Zealand', continent: 'Oceania' },
  { code: 'CHC', name: 'Christchurch International Airport', city: 'Christchurch', country: 'New Zealand', continent: 'Oceania' },
  { code: 'NAN', name: 'Nadi International Airport', city: 'Nadi', country: 'Fiji', continent: 'Oceania' },
  { code: 'FUN', name: 'Funafuti International Airport', city: 'Funafuti', country: 'Tuvalu', continent: 'Oceania' },
  { code: 'POM', name: 'Port Moresby Jacksons International Airport', city: 'Port Moresby', country: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'HIR', name: 'Honiara International Airport', city: 'Honiara', country: 'Solomon Islands', continent: 'Oceania' },
  { code: 'TRW', name: 'Bonriki International Airport', city: 'Tarawa', country: 'Kiribati', continent: 'Oceania' },
  { code: 'INU', name: 'Nauru International Airport', city: 'Yaren', country: 'Nauru', continent: 'Oceania' },
  { code: 'VLI', name: 'Bauerfield International Airport', city: 'Port Vila', country: 'Vanuatu', continent: 'Oceania' },
  { code: 'NOU', name: 'La Tontouta International Airport', city: 'Nouméa', country: 'New Caledonia', continent: 'Oceania' },
  { code: 'TBU', name: 'Fuaʻamotu International Airport', city: 'Nukuʻalofa', country: 'Tonga', continent: 'Oceania' },
  { code: 'PPG', name: 'Pago Pago International Airport', city: 'Pago Pago', country: 'American Samoa', continent: 'Oceania' },
  { code: 'RAR', name: 'Rarotonga International Airport', city: 'Rarotonga', country: 'Cook Islands', continent: 'Oceania' },
  { code: 'APW', name: 'Faleolo International Airport', city: 'Apia', country: 'Samoa', continent: 'Oceania' },
  { code: 'GEA', name: 'Nouméa Magenta Airport', city: 'Nouméa', country: 'New Caledonia', continent: 'Oceania' },
  { code: 'GUM', name: 'Guam Antonio B. Won Pat International Airport', city: 'Hagåtña', country: 'Guam', continent: 'Oceania' },
  { code: 'SPN', name: 'Saipan International Airport', city: 'Saipan', country: 'Northern Mariana Islands', continent: 'Oceania' },
  { code: 'ROR', name: 'Palau Roman Tmetuchl International Airport', city: 'Koror', country: 'Palau', continent: 'Oceania' },

  // Russia
  { code: 'SVO', name: 'Moscow Sheremetyevo International Airport', city: 'Moscow', country: 'Russia', continent: 'Europe' },
  { code: 'DME', name: 'Moscow Domodedovo Airport', city: 'Moscow', country: 'Russia', continent: 'Europe' },
  { code: 'VKO', name: 'Moscow Vnukovo Airport', city: 'Moscow', country: 'Russia', continent: 'Europe' },
  { code: 'LED', name: 'Saint Petersburg Pulkovo Airport', city: 'Saint Petersburg', country: 'Russia', continent: 'Europe' },
  { code: 'OVB', name: 'Novosibirsk Tolmachevo Airport', city: 'Novosibirsk', country: 'Russia', continent: 'Asia' },
  { code: 'SVX', name: 'Yekaterinburg Koltsovo Airport', city: 'Yekaterinburg', country: 'Russia', continent: 'Europe' },
  { code: 'VVO', name: 'Vladivostok International Airport', city: 'Vladivostok', country: 'Russia', continent: 'Asia' },
  { code: 'IKT', name: 'Irkutsk International Airport', city: 'Irkutsk', country: 'Russia', continent: 'Asia' },
  { code: 'KZN', name: 'Kazan International Airport', city: 'Kazan', country: 'Russia', continent: 'Europe' },
  { code: 'AER', name: 'Sochi International Airport', city: 'Sochi', country: 'Russia', continent: 'Europe' },
  { code: 'UFA', name: 'Ufa International Airport', city: 'Ufa', country: 'Russia', continent: 'Europe' },
  { code: 'CEK', name: 'Chelyabinsk Airport', city: 'Chelyabinsk', country: 'Russia', continent: 'Europe' },
  { code: 'KUF', name: 'Samara Kurumoch Airport', city: 'Samara', country: 'Russia', continent: 'Europe' },
  { code: 'KJA', name: 'Krasnoyarsk Yemelyanovo Airport', city: 'Krasnoyarsk', country: 'Russia', continent: 'Asia' },
  { code: 'OMS', name: 'Omsk Tsentralny Airport', city: 'Omsk', country: 'Russia', continent: 'Asia' },
  { code: 'ROV', name: 'Rostov-on-Don Platov International Airport', city: 'Rostov-on-Don', country: 'Russia', continent: 'Europe' },
  { code: 'VOG', name: 'Volgograd International Airport', city: 'Volgograd', country: 'Russia', continent: 'Europe' },
  { code: 'MMK', name: 'Murmansk Airport', city: 'Murmansk', country: 'Russia', continent: 'Europe' },
  { code: 'ARH', name: 'Arkhangelsk Talagi Airport', city: 'Arkhangelsk', country: 'Russia', continent: 'Europe' },
  { code: 'PKC', name: 'Petropavlovsk-Kamchatsky Yelizovo Airport', city: 'Petropavlovsk-Kamchatsky', country: 'Russia', continent: 'Asia' },
  { code: 'GDX', name: 'Magadan Sokol Airport', city: 'Magadan', country: 'Russia', continent: 'Asia' },
  { code: 'NSK', name: 'Norilsk Alykel Airport', city: 'Norilsk', country: 'Russia', continent: 'Asia' },
  { code: 'YKS', name: 'Yakutsk Airport', city: 'Yakutsk', country: 'Russia', continent: 'Asia' },
  { code: 'HTA', name: 'Chita Kadala Airport', city: 'Chita', country: 'Russia', continent: 'Asia' },
  { code: 'BQS', name: 'Blagoveshchensk Ignatyevo Airport', city: 'Blagoveshchensk', country: 'Russia', continent: 'Asia' },
  { code: 'KHV', name: 'Khabarovsk Novy Airport', city: 'Khabarovsk', country: 'Russia', continent: 'Asia' },
  { code: 'DYR', name: 'Anadyr Ugolny Airport', city: 'Anadyr', country: 'Russia', continent: 'Asia' },
  { code: 'BTK', name: 'Bratsk Airport', city: 'Bratsk', country: 'Russia', continent: 'Asia' },
  { code: 'ABA', name: 'Abakan International Airport', city: 'Abakan', country: 'Russia', continent: 'Asia' },
  { code: 'SGC', name: 'Surgut International Airport', city: 'Surgut', country: 'Russia', continent: 'Asia' },
  { code: 'NJC', name: 'Nizhnevartovsk Airport', city: 'Nizhnevartovsk', country: 'Russia', continent: 'Asia' },
  { code: 'TJM', name: 'Tyumen Roshchino International Airport', city: 'Tyumen', country: 'Russia', continent: 'Asia' },
  { code: 'BAX', name: 'Barnaul Airport', city: 'Barnaul', country: 'Russia', continent: 'Asia' },
  { code: 'TOF', name: 'Tomsk Bogashevo Airport', city: 'Tomsk', country: 'Russia', continent: 'Asia' },
  { code: 'EGO', name: 'Belgorod International Airport', city: 'Belgorod', country: 'Russia', continent: 'Europe' },
  { code: 'BZK', name: 'Bryansk International Airport', city: 'Bryansk', country: 'Russia', continent: 'Europe' },
  { code: 'REN', name: 'Orenburg Tsentralny Airport', city: 'Orenburg', country: 'Russia', continent: 'Europe' },
  { code: 'ASF', name: 'Astrakhan Narimanovo Airport', city: 'Astrakhan', country: 'Russia', continent: 'Europe' },
  { code: 'IWA', name: 'Ivanovo Yuzhny Airport', city: 'Ivanovo', country: 'Russia', continent: 'Europe' },
  { code: 'IAR', name: 'Yaroslavl Tunoshna Airport', city: 'Yaroslavl', country: 'Russia', continent: 'Europe' },
  { code: 'LPK', name: 'Lipetsk Airport', city: 'Lipetsk', country: 'Russia', continent: 'Europe' },
  { code: 'VOZ', name: 'Voronezh International Airport', city: 'Voronezh', country: 'Russia', continent: 'Europe' },
  { code: 'KLF', name: 'Kaluga Grabtsevo Airport', city: 'Kaluga', country: 'Russia', continent: 'Europe' },
  { code: 'URS', name: 'Kursk Vostochny Airport', city: 'Kursk', country: 'Russia', continent: 'Europe' },
  { code: 'KLD', name: 'Tver Migalovo Air Base', city: 'Tver', country: 'Russia', continent: 'Europe' },
  { code: 'LNX', name: 'Smolensk South Airport', city: 'Smolensk', country: 'Russia', continent: 'Europe' },

  // Additional European Countries
  { code: 'KIV', name: 'Chișinău International Airport', city: 'Chișinău', country: 'Moldova', continent: 'Europe' },
  { code: 'GIB', name: 'Gibraltar Airport', city: 'Gibraltar', country: 'Gibraltar', continent: 'Europe' },
  { code: 'FAE', name: 'Vágar Airport', city: 'Tórshavn', country: 'Faroe Islands', continent: 'Europe' },
  { code: 'GOH', name: 'Nuuk Airport', city: 'Nuuk', country: 'Greenland', continent: 'North America' },
  { code: 'KBP', name: 'Kyiv Boryspil International Airport', city: 'Kyiv', country: 'Ukraine', continent: 'Europe' },
  { code: 'LWO', name: 'Lviv Danylo Halytskyi International Airport', city: 'Lviv', country: 'Ukraine', continent: 'Europe' },
  { code: 'ODS', name: 'Odessa International Airport', city: 'Odessa', country: 'Ukraine', continent: 'Europe' },
  { code: 'SIP', name: 'Simferopol International Airport', city: 'Simferopol', country: 'Crimea', continent: 'Europe' },
  { code: 'MSQ', name: 'Minsk National Airport', city: 'Minsk', country: 'Belarus', continent: 'Europe' },
  { code: 'KGD', name: 'Kaliningrad Khrabrovo Airport', city: 'Kaliningrad', country: 'Russia', continent: 'Europe' },
  { code: 'AQJ', name: 'King Hussein International Airport', city: 'Aqaba', country: 'Jordan', continent: 'Middle East' },
  { code: 'ETM', name: 'Eilat Ramon Airport', city: 'Eilat', country: 'Israel', continent: 'Middle East' },
  { code: 'LYR', name: 'Longyearbyen Svalbard Airport', city: 'Longyearbyen', country: 'Norway', continent: 'Europe' }
];

export const searchAirports = (query: string): Airport[] => {
  if (!query || query.length < 2) return [];
  
  const searchTerm = query.toLowerCase();
  
  return AIRPORTS.filter(airport => 
    airport.code.toLowerCase().includes(searchTerm) ||
    airport.name.toLowerCase().includes(searchTerm) ||
    airport.city.toLowerCase().includes(searchTerm) ||
    airport.country.toLowerCase().includes(searchTerm)
  ).slice(0, 10);
};

export const getAirportByCode = (code: string): Airport | undefined => {
  return AIRPORTS.find(airport => airport.code === code);
};
